[theme]

# Primary accent for interactive elements
primaryColor = '#9ACD32'

# Background color for the main content area
backgroundColor =  '#0000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#111'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"